### ISSUE TITLE
Bug in functions called by "dispersal.kernel"?

### ISSUE THREAD

**Issue by opl100** [apferreira/dispfit#3]
Hello,

I would like to report a possible bug in the dispfit package, downloaded from Github on 12/04/2022. 

I try to run the example included in the documnetation for the "dispersal.kernel" function:

 ## simulate data from lognormal distribution
set.seed(1111)
simulated.data <- rlnorm(200, meanlog = 5, sdlog = 1)

## run dispersal.kernel function
fit <- dispersal.kernel(simulated.data)

This produces the error message:
Error in exponential.function(kernel.fit$data, chi.res.hist, ks.res.hist,: object 'dist.exponential.opt' not found

Looking at code for the function "exponential.function", which is called by "dispersal.kernel", it appears that the error occurs because the object 'dist.exponential.opt' is not defined anywhere. Hence, I am wondering if this is a bug, where 'dist.exponential.opt' should have another name. Trying with the other functions separately, it appears that the same problem exists for the follwoing functions:
general normal
2Dt
wald
weibull

All the best,
Ole Petter Vindstad

**Comment by apferreira** [comment]
Hi Ole,

Thanks for your message.

It seems to be indeed a bug from a correction I've made to some estimates a month ago.

I've just updated the function. Can you please check if it now runs correctly?

Cheers,
António

**Comment by opl100** [comment]
Thank you! This fixed the problem for the exponential function, but I still have error messages for some functions. These are as follows:

general normal: Error in data.frame(aic.generalnormal, aicc.generalnormal, bic.generalnormal,  : object 'mean.stderr.generalnormal' not found

2Dt: Error in twodt.function(kernel.fit$data, chi.res.hist, ks.res.hist, confidence.level) : 
  object 'dist.2dt.opt' not found

Wald: rror in wald.function(kernel.fit$data, chi.res.hist, ks.res.hist, confidence.level) : 
  object 'dist.wald.opt' not found

Weibull: Error in weibull.function(kernel.fit$data, chi.res.hist, ks.res.hist,  : 
  object 'dist.weibull.opt' not found
 
The other functions seem to work fine.

Cheers 
Ole Petter

**Comment by apferreira** [comment]
Thanks, I've corrected the others as well.

Please confirm if everything is running now.

Cheers,
António

**Comment by opl100** [comment]
It all runs smoothly now. Thanks for the extraordinarily quick handling of the issue. Much appreciated!
All the best,
Ole Petter

**Comment by apferreira** [comment]
You're welcome, thanks for trying the package!

(you also got me at a less busy moment, lucky for both of us!)

Take care,
António
